version: '3'

services:
  postgres-db:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_USER: mealie
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mealiedb
    volumes:
      - mealie-db-volume:/var/lib/postgresql/data
  backend:
    image: dashwav/mealiebackend:stable
    command: ["/usr/local/bin/backend", "serve", "--migrate"]
    ports:
      - "8810:8810"
    environment:
      - MEALIE_DATABASE_URL=postgresql://mealie:password@postgres-db:5432/mealiedb?sslmode=disable
      - MEALIE_PORT=0.0.0.0:8810
    volumes:
      - "./:/etc/mealiebackend"
    depends_on:
      - postgres-db

volumes:
  mealie-db-volume: